// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDWva_djHMCaMYOjqaHAM8ccR-_C2HMs',
    appId: '1:308264747529:android:31527d23ea9bb9b9bdaed8',
    messagingSenderId: '308264747529',
    projectId: 'ehrsystem-32674f7e',
    storageBucket: 'ehrsystem-32674f7e.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZKHOA0QbO_y-xCB79myqG6-O-cbhIWU',
    appId: '1:308264747529:web:a6062fe62e73860bbdaed8',
    messagingSenderId: '308264747529',
    projectId: 'ehrsystem-32674f7e',
    authDomain: 'ehrsystem-32674f7e.firebaseapp.com',
    storageBucket: 'ehrsystem-32674f7e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfZKHOA0QbO_y-xCB79myqG6-O-cbhIWU',
    appId: '1:308264747529:web:d64203aa90e99457bdaed8',
    messagingSenderId: '308264747529',
    projectId: 'ehrsystem-32674f7e',
    authDomain: 'ehrsystem-32674f7e.firebaseapp.com',
    storageBucket: 'ehrsystem-32674f7e.firebasestorage.app',
  );
}
